spring:
  application:
    name: eureka-service

server:
  port: 8303
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
zuul:
  prefix: /api
  routes:
    customer-service:
      path: /customer-service/**
      url: http://localhost:8300
    item-service:
      path: /item-service/**
      url: http://localhost:8301      
            